CONFIG_ZMK_LEADER_MAX_KEYS_PER_SEQUENCE=5
CONFIG_ZMK_LEADER_TIMEOUT_MS=1400

# Enable ZMK Studio
#CONFIG_ZMK_STUDIO=y

# Optional: Studio locking settings
#CONFIG_ZMK_STUDIO_LOCKING=y
#CONFIG_ZMK_STUDIO_LOCK_IDLE_TIMEOUT_SEC=300
#CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=y

# Required for Studio to work properly
#CONFIG_ZMK_STUDIO_RPC=y
